### ISSUE TITLE
Kubernetes Support

### ISSUE THREAD

**Issue by leadaenschel** [xainag/xain-fl#261]
**Question via e-mail:** 

> One of the deployments we are looking at requires Kubernetes 1.15.  I am trying to ensure that everything will work nicely together via the version issues that we have encountered with Kubernetes so far.  Do you have a recommendation for a Centos 8 or Centos 7 stack?  I want to ensure that I have the right Docker version, Kubernetes version and Xain version to ensure that it works without unforeseen issues.

**Comment by dkravetz** [comment]
As of right now, we're not hosting in Kubernetes. Whenever we start using k8s, the documentation will be updated accordingly.
Regarding the underlying operating system, that shouldn't be a problem. However, we use Ubuntu for our servers, can't know for sure about CentOS/RedHat

**Comment by leadaenschel** [comment]
To add to that, for the open source stack we provide docker images, which gives you the flexibility to deploy it your way. We also provide a fully managed solution of XAIN and here we work with more specific deployements for us. We will provide the Kubernetes support approximately in Spring 2020.

**Comment by Robert-Steiner** [comment]
I'm closing this issue because Kubernetes is now part of the repository. (since version 0.8.0)
