### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#316]
This should be broken into multiple issues, but at a high level we should have:

- [X] unit tests for the protocol itself
- [ ] integration tests with a client handle (ie without the ReST and RPC layers)
- [ ] end to end tests (maybe in Python?)

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue/solution relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. A similar issue may have occurred in the upcoming version, but it will be addressed in a separate issue.
