### ISSUE TITLE
Handle lost end training message

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#324]
We need to clarify what the expected behavior is for the following scenario:

- `P` uploads their weights
- `A::add_weights` is called, the weights are validated
- `A` sends an end training message to `C` for `P`, which gets lost due to network issues

I can see three ways to handle this:

1. `A` could keeps trying. But by the time communication is established again, `P` may have been removed already, so `C` will just reject the message. I'm not sure where to go from there.
2. `A` ignores the lost message an continue. The aggregator would then have more weights than expected but is that really an issue?
3. `A` aborts the round, and notify the coordinator. `A` rejects every message until `C` acknowledges the round reset. That seems like the best solution but  requires adding new RPC methods.

For now we'll go with solution `2.`

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. In the new upcoming version, the aggregator is part of the  coordinator so that the problems mentioned here no longer apply.
