### ISSUE TITLE
Add synchronisation mechanism

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#325]
If either `A` or `C` goes down, or even if the network goes down for a few minutes and some messages are lost, `A` and `C` need to synchronize again. The simplest way to do that I believe is to reset the current round.

Potentially related:

- https://github.com/xainag/coordinator-rs/issues/18
- https://github.com/xainag/coordinator-rs/issues/15
- https://github.com/xainag/coordinator-rs/issues/10

**Comment by JameerBabu** [comment]
Can I work on this issue

**Comment by janpetschexain** [comment]
hi, sorry for the late reply. we are currently working on the integration of a secure computation layer (in the `pet` branch) and aim to merge this into master in the next weeks. this makes some of the open issues obsolete, for example coordinator and aggregator services are merged into one, and we will clean up those issue.

nevertheless, your offer is highly appreciated and you might find other interesting issues after the integration.

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue/solution relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. In the upcoming version, the aggregator is part of the coordinator therefore no synchronization is required .
