### ISSUE TITLE
Clarify how service errors should be handled

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#329]
When the HTTP layer sends a requests to our service, but the service fails to answer it (because the RPC is down for instance), we currently just drop the response channel, which the HTTP layer converts into a `502`. That seems a bit dirty so maybe we should have a proper result type, but I'm not sure how much boilerplate this would add.

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue/solution relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. A similar issue may have occurred in the upcoming version, but it will be addressed in a separate issue.
