### ISSUE TITLE
Add timeouts for "start training" and "end training"

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#332]
We should start ignoring a participant if they never send their "start training" request, or never upload their results so avoid starving the coordinator. Note that this is a little tricky for "end training" requests because we have to make sure to synchronize the state between the aggregator and the coordinator. See: https://github.com/xainag/coordinator-rs/issues/10

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. However, a similar issue is still present in the upcoming version. It will be resolved by PB-843.
