### ISSUE TITLE
Mitigate DoS on the aggregator

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#333]
Currently, a participant can start multiple downloads or uploads concurrently. If the weights are big this can lead to poor download/upload rates for everyone. We could prevent this by checking whether a participant is already uploading/downloading and prevent them from starting a new operation.

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue/solution relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. A similar issue may have occurred in the upcoming version, but it will be addressed in a separate issue.
