### ISSUE TITLE
asking for some examples or tutorials 

### ISSUE THREAD

**Issue by fermat97** [xainag/xain-fl#378]
Hi, I am wondering if there are some examples or tutorials for implementing the federated learning with secure aggregation (for instance via SMPC). I have just found one which I think is the naive federated learning.  Thank you.

**Comment by little-dude** [comment]
Hi @fermat97,

The latest release (0.8) and the `master` branch of this repo do not implement secure aggregation. We're currently working on this though, and we'll try to make a first release of this in a couple weeks.

We do have tutorial for implementing participants based for our current backend though: https://xain-fl.readthedocs.io/projects/xain-sdk/en/latest/tutorial.html

**Comment by fermat97** [comment]
Thank you. Is that based on SMPC or some other solutions?

**Comment by little-dude** [comment]
No, currenlty the implementation is very simple: the backend collects all the models from the participants and aggregates them. We are currently working on an SMPC solution, which we hope to release in a couple weeks.

**Comment by Robert-Steiner** [comment]
I'm closing this issue because it has been inactive for a few weeks. The coming version of the coordinator implements the PET protocol described in the white paper mentioned above. Feel free to open a new ticket if you have any questions.

Thank you!
